FROM centos

MAINTAINER Subasri

RUN mkdir /opt/tomcat/

WORKDIR /opt/tomcat
RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.60/bin/apache-tomcat-9.0.60.tar.gzn/apache-tomcat-8.5.40.tar.gz
RUN tar -zvxf apache-tomcat-9.0.10.tar.gz
RUN mv apache-tomcat-9.0.10 /opt/tomcat/.
RUN yum -y install java
RUN java -version

WORKDIR /opt/tomcat/webapps
RUN curl -O -L https://github.com/suba23/SampleWebApp.git

EXPOSE 8080

CMD ["/opt/tomcat/bin/catalina.sh", "run"]